language: python

matrix:
  include:
    - python: "3.6"
      os: linux

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      sudo apt-get update;
    fi

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q conda-build
  # Useful for debugging any issues with conda
  - conda info -a

  # conda channels
  - conda config --append channels conda-forge
  - conda config --append channels cmutel
  - conda config --append channels haasad

  # conda build
  - conda build ./conda-recipe/

  # install
  - conda install --use-local eidl

script:
  - python -c "import eidl"

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then 
      conda install anaconda-client;
      cp /home/travis/miniconda/conda-bld/noarch/*.tar.bz2 .;
      anaconda -t $CONDA_TOKEN upload --force *.tar.bz2;
      echo "uploaded to conda channel";
    else
      echo "no upload because not master branch";
    fi

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
