name: conda-release

on:
  push:
    branches:
    - master
    - gh-actions
    tags:
    - v*
  pull_request:
    branches:
     - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up miniconda with python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        auto-activate-base: false
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Add conda channels
      shell: bash -l {0}
      run: |
        conda config --prepend channels conda-forge
        conda config --append channels cmutel
        conda config --append channels haasad
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install brightway2 requests beautifulsoup4 eidl7zip appdirs
    - name: Test
      shell: bash -l {0}
      run: |
        python -c "import eidl"

  build-and-release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - name: Set up miniconda with python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Add conda channels
      shell: bash -l {0}
      run: |
        conda config --prepend channels conda-forge
        conda config --append channels cmutel
        conda config --append channels haasad
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install conda-build anaconda-client
    - name: Build conda package
      shell: bash -l {0}
      run: |
        conda build ./conda-recipe/
    - name: Upload to haasad conda channel
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash -l {0}
      run: |
        anaconda upload -t ${{ secrets.CONDA_TOKEN }} /usr/share/miniconda/envs/test/conda-bld/noarch/eidl-*.tar.bz2
