name: release
on:
  push:
    tags:
      - v*

jobs:
  changelog-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build changelog from PRs with labels
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: ".github/changelog-configuration.json"
          # PreReleases still get a changelog, but the next full release gets a diff since the last full release,
          # combining possible changelogs of all previous PreReleases in between.
          # PreReleases show a partial changelog since last PreRelease.
          ignorePreReleases: "${{ !contains(github.ref, '-rc') }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          prerelease: "${{ contains(github.ref, '-rc') }}"
          # Ensure target branch for release is "master"
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-conda-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: build
          environment-file: .github/environment-build.yaml
      - name: Build conda package
        shell: bash -l {0}
        run: |
          conda build ./conda-recipe/
      - name: Upload to haasad conda channel
        shell: bash -l {0}
        run: |
          anaconda -t ${{ secrets.CONDA_TOKEN }} upload \
          /usr/share/miniconda/envs/build/conda-bld/noarch/*.tar.bz2
